---
version: '3'

dotenv: ['.env']

vars:
  dir: '{{.USER_WORKING_DIR}}'
  default_render_format: "stl"
  default_render_resolution: 100

  default_bitmap_format: "png"
  default_bitmap_size_x: 1024
  default_bitmap_size_y: 768

tasks:
  default:
    cmds:
      - task: all

  all:
    desc: "Render all SCAD files in the current directory"
    vars:
      format: "{{.RENDER_FORMAT | default .default_render_format}}"
      resolution: "{{.RENDER_RESOLUTION | default .default_render_resolution}}"
    cmds:
      - |
        set -e
        for _FILE in $(ls {{.dir}}/*.scad); do
          task render -- "${_FILE}"
        done

      - |
        set -e
        for _FILE in $(ls {{.dir}}/*.scad); do
          task bitmap -- "${_FILE}"
        done

  render:
    desc: "Render a single SCAD file"
    vars:
      format: "{{.RENDER_FORMAT | default .default_render_format}}"
      resolution: "{{.RENDER_RESOLUTION | default .default_render_resolution}}"
      file: "{{.CLI_ARGS}}"
    cmds:
      - |
        set -e
        [[ -z "{{.file}}" ]] && echo "No file specified" && exit 1
        echo "Rendering '{{.file}}' into '{{.format}}' format with a resolution of '{{.resolution}}'"
        cd "{{.dir}}"
        _EXPORT_FILE="$(dirname "{{.file}}")/$(basename "{{.file}}" .scad).{{.format}}"
        openscad -o "${_EXPORT_FILE}" -D '$fn={{.resolution}}' "{{.file}}"

  bitmap:
    desc: "Create bitmap image from SCAD file"
    vars:
      format: "{{.BITMAP_FORMAT | default .default_bitmap_format}}"
      resolution: "{{.RENDER_RESOLUTION | default .default_render_resolution}}"
      size_x: "{{.BITMAP_SIZE_X | default .default_bitmap_size_x}}"
      size_y: "{{.BITMAP_SIZE_Y | default .default_bitmap_size_y}}"
      file: "{{.CLI_ARGS}}"
    cmds:
        - |
            set -e
            [[ -z "{{.file}}" ]] && echo "No file specified" && exit 1
            echo "Creating bitmap image from '{{.file}}' with a resolution of '{{.size_x}}x{{.size_y}}'"
            cd "{{.dir}}"
            _EXPORT_FILE="$(dirname "{{.file}}")/$(basename "{{.file}}" .scad).{{.format}}"
            openscad -o "${_EXPORT_FILE}" --viewall --autocenter --imgsize="{{.size_x}},{{.size_y}}" -D '$fn={{.resolution}}' "{{.file}}"
