---
version: '3'

dotenv: ['.env']

vars:
  dir: '{{.USER_WORKING_DIR}}'
  default_format: "stl"
  default_resolution: 100

tasks:
  default:
    cmds:
      - task: render

  render:
    desc: "Render all SCAD files in the current directory"
    vars:
      format: "{{.FORMAT | default .default_format}}"
      resolution: "{{.RESOLUTION | default .default_resolution}}"
    cmds:
      - |
        set -e
        echo "Rendering all SCAD files into '{{.format}}' format with a resolution of '{{.resolution}}'"
        for _FILE in $(ls {{.dir}}/*.scad); do
          _EXPORT_FILE="{{.dir}}/$(basename "${_FILE}" .scad).{{.format}}"
          echo "Rendering '${_FILE}' into '${_EXPORT_FILE}, resolution: {{.resolution}}'"
          openscad -o "${_EXPORT_FILE}" -D '$fn={{.resolution}}' "${_FILE}"
        done
